# Generated by Django 5.0.4 on 2024-04-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0004_tribute_imagecomment_tributecomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagepost',
            name='image',
        ),
        migrations.RemoveField(
            model_name='imagepost',
            name='title',
        ),
        migrations.AddField(
            model_name='imagepost',
            name='date',
            field=models.DateTimeField(auto_now_add=True,),
            preserve_default=False,
        ),
    ]
