# Generated by Django 5.0.4 on 2024-04-20 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_remove_imagepost_image_remove_imagepost_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribute',
            name='email',
        ),
        migrations.AddField(
            model_name='tribute',
            name='relationship',
            field=models.CharField(blank=True, choices=[('son', 'son'), ('daughter', 'daughter'), ('son_inlaw', 'son inlaw'), ('daughter_inlaw', 'daughter inlaw'), ('grand_child', 'grand child'), ('sibling', 'sibling'), ('friends', 'friends'), ('family_friend', 'family friend'), ('friends_children', 'friends_of_children')], max_length=30, null=True),
        ),
    ]
