# Generated by Django 5.0.4 on 2024-04-20 12:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0006_remove_tribute_email_tribute_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecomment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tribute',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='tributecomment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tribute',
            name='relationship',
            field=models.CharField(blank=True, choices=[('', 'Select relationship status'), ('son', 'son'), ('daughter', 'daughter'), ('son_inlaw', 'son inlaw'), ('daughter_inlaw', 'daughter inlaw'), ('grand_child', 'grand child'), ('sibling', 'sibling'), ('friends', 'friends'), ('family_friend', 'family friend'), ('friends_children', 'friends_of_children')], max_length=30, null=True),
        ),
    ]
