# Generated by Django 5.0.4 on 2024-04-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0007_imagecomment_date_tribute_date_tributecomment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tribute',
            name='relationship',
            field=models.CharField(blank=True, choices=[('', 'Select relationship status'), ('son', 'son'), ('daughter', 'daughter'), ('son inlaw', 'son_inlaw'), ('daughter_inlaw', 'daughter_inlaw'), ('grand child', 'grand_child'), ('sibling', 'sibling'), ('friends', 'friends'), ('family friend', 'family_friend'), ('friends children', 'friends_of_children')], max_length=30, null=True),
        ),
    ]
