# Generated by Django 5.0.4 on 2024-04-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0009_alter_tribute_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagepost',
            name='caption',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
